import "./globals.css";
import Header from "@/components/Header";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/components/Footer";
/*
const rubik = Rubik({
  subsets: ['latin'], // Choose subsets as needed
  weight: ['400', '500', '700'], // Specify font weights
});*/


export const metadata = {
  title: "DentaLink",
  description: "Generated by donia",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <link
        href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;700&display=swap"
        rel="stylesheet"
      />
    </head>
    <body className="antialiased font-rubik min-h-screen flex flex-col">
      {/* Header */}
      <Header />

      {/* Main Content */}
      <main className="flex-grow">
        {children}
      </main>

      {/* Footer */}
      <Footer />
    </body>
  </html>
  );
}
